from pathlib import Path

FEATURE_MAP_DIR = Path("data/feature_maps")

PATCH_SIZE = 80
PADDING_SIZE = 10
NUM_PATCH_PAIRS = 1000
INITIAL_PATCH_PAIR = 250
PATCH_STRIDE = 16

INITIAL_NUM_CENTROIDS = 8
MAX_NUM_CENTROIDS = 32
INITIAL_KDE_RHO = 0.8

INITIAL_NUM_ITERATIONS = 20
MAX_NUM_ITERATIONS = 200

MAX_SMOOTHNESS = 20000
INITIAL_SMOOTHNESS = 2000
SMOOTHNESS_STEP = 100